## Job Description Dataset Embedding

In [11]:
import pandas as pd

In [12]:
jd_df = pd.read_excel("../1_data_cleaning/filtered_jd_sections2.xlsx")

In [13]:
jd_df.head()

,job_description,location_cleaned,job_title,jd_duties,jd_requirements,jd_education
0,Job SummaryDo you have a strong aptitude for w...,"Natick, MA",Content Developer for MATLAB Code Generation,Software components make up an ever larger par...,Job SummaryDo you have a strong aptitude for w...,Minimum Qualifications A bachelor's degree and...
1,Overview External: Chevron is one of the world...,"Houston, TX",Land Assistant,Overview External: Chevron is one of the world...,"Prepare, and secure appropriate approvals for ...",Preferred Qualifications: Bachelor's degree
2,Overview: The Hartman Non-Profit is seeking to...,"Houston, TX",Project Manager,Overview: The Hartman Non-Profit is seeking to...,Required Abilities and Experience: · A strong ...,· A minimum of a Bachelor’s degree in a busine...
3,City: Houston State:Texas Postal/Zip Code: 770...,"Houston, TX",Asphalt Quality Control Manager -Houston,Our operations span the nation from Montana to...,Other Requirements Display a professional and ...,Qualifications Bachelor’s degree (B
4,Hiring! Immediate openings for Customer Suppor...,"San Antonio, TX",Customer Support Specialist!,Immediate openings for Customer Support Specia...,Hiring\nWe want your excellent customer servic...,High School Diploma/GED

In [14]:
# create semantic sentence for each row
def build_semantic_sentence(row):
    desc = str(row["job_description"])
    loc  = str(row["location_cleaned"])
    title = str(row["job_title"])
    duties = str(row["jd_duties"])
    req = str(row["jd_requirements"])
    edu = str(row["jd_education"])

    return (
        f"This job, titled {title} and located in {loc}, involves {duties}. "
        f"The role description states: {desc}. "
        f"Applicants are expected to meet the following requirements: {req}. "
        f"The position lists the following educational background: {edu}."
    )

jd_df["semantic_sentence"] = jd_df.apply(build_semantic_sentence, axis=1)
jd_df.head()

,job_description,location_cleaned,job_title,jd_duties,jd_requirements,jd_education,semantic_sentence
0,Job SummaryDo you have a strong aptitude for w...,"Natick, MA",Content Developer for MATLAB Code Generation,Software components make up an ever larger par...,Job SummaryDo you have a strong aptitude for w...,Minimum Qualifications A bachelor's degree and...,"This job, titled Content Developer for MATLAB ..."
1,Overview External: Chevron is one of the world...,"Houston, TX",Land Assistant,Overview External: Chevron is one of the world...,"Prepare, and secure appropriate approvals for ...",Preferred Qualifications: Bachelor's degree,"This job, titled Land Assistant and located in..."
2,Overview: The Hartman Non-Profit is seeking to...,"Houston, TX",Project Manager,Overview: The Hartman Non-Profit is seeking to...,Required Abilities and Experience: · A strong ...,· A minimum of a Bachelor’s degree in a busine...,"This job, titled Project Manager and located i..."
3,City: Houston State:Texas Postal/Zip Code: 770...,"Houston, TX",Asphalt Quality Control Manager -Houston,Our operations span the nation from Montana to...,Other Requirements Display a professional and ...,Qualifications Bachelor’s degree (B,"This job, titled Asphalt Quality Control Manag..."
4,Hiring! Immediate openings for Customer Suppor...,"San Antonio, TX",Customer Support Specialist!,Immediate openings for Customer Support Specia...,Hiring\nWe want your excellent customer servic...,High School Diploma/GED,"This job, titled Customer Support Specialist! ..."

In [15]:
from sentence_transformers import SentenceTransformer
import torch

model = SentenceTransformer("all-MiniLM-L6-v2")

In [16]:
def embed_sentence(sentence):
    return model.encode(sentence)
jd_df["semantic_emb"] = jd_df["semantic_sentence"].apply(embed_sentence)
jd_df.head()

,job_description,location_cleaned,job_title,jd_duties,jd_requirements,jd_education,semantic_sentence,semantic_emb
0,Job SummaryDo you have a strong aptitude for w...,"Natick, MA",Content Developer for MATLAB Code Generation,Software components make up an ever larger par...,Job SummaryDo you have a strong aptitude for w...,Minimum Qualifications A bachelor's degree and...,"This job, titled Content Developer for MATLAB ...","[-0.11898153, 0.022940144, -0.0019065854, -0.0..."
1,Overview External: Chevron is one of the world...,"Houston, TX",Land Assistant,Overview External: Chevron is one of the world...,"Prepare, and secure appropriate approvals for ...",Preferred Qualifications: Bachelor's degree,"This job, titled Land Assistant and located in...","[-0.05651948, -0.0052046115, 0.052328493, 0.06..."
2,Overview: The Hartman Non-Profit is seeking to...,"Houston, TX",Project Manager,Overview: The Hartman Non-Profit is seeking to...,Required Abilities and Experience: · A strong ...,· A minimum of a Bachelor’s degree in a busine...,"This job, titled Project Manager and located i...","[-0.0018582594, -0.005258763, -0.048782453, 0...."
3,City: Houston State:Texas Postal/Zip Code: 770...,"Houston, TX",Asphalt Quality Control Manager -Houston,Our operations span the nation from Montana to...,Other Requirements Display a professional and ...,Qualifications Bachelor’s degree (B,"This job, titled Asphalt Quality Control Manag...","[-0.054384027, -0.015934534, 0.09139241, 0.031..."
4,Hiring! Immediate openings for Customer Suppor...,"San Antonio, TX",Customer Support Specialist!,Immediate openings for Customer Support Specia...,Hiring\nWe want your excellent customer servic...,High School Diploma/GED,"This job, titled Customer Support Specialist! ...","[-0.117414355, 0.0009043607, 0.08832788, 0.033..."