## Data exploration

In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [19]:
jd_df = pd.read_csv('datasets/job_description.csv')

In [20]:
jd_df.head()

,country,country_code,date_added,has_expired,job_board,job_description,job_title,job_type,location,organization,page_url,salary,sector,uniq_id
0,United States of America,US,NaN,No,jobs.monster.com,TeamSoft is seeing an IT Support Specialist to...,IT Support Technician Job in Madison,Full Time Employee,"Madison, WI 53702",NaN,http://jobview.monster.com/it-support-technici...,NaN,IT/Software Development,11d599f229a80023d2f40e7c52cd941e
1,United States of America,US,NaN,No,jobs.monster.com,The Wisconsin State Journal is seeking a flexi...,Business Reporter/Editor Job in Madison,Full Time,"Madison, WI 53708",Printing and Publishing,http://jobview.monster.com/business-reporter-e...,NaN,NaN,e4cbb126dabf22159aff90223243ff2a
2,United States of America,US,NaN,No,jobs.monster.com,Report this job About the Job DePuy Synthes Co...,Johnson & Johnson Family of Companies Job Appl...,"Full Time, Employee",DePuy Synthes Companies is a member of Johnson...,Personal and Household Services,http://jobview.monster.com/senior-training-lea...,NaN,NaN,839106b353877fa3d896ffb9c1fe01c0
3,United States of America,US,NaN,No,jobs.monster.com,Why Join Altec? If you’re considering a career...,Engineer - Quality Job in Dixon,Full Time,"Dixon, CA",Altec Industries,http://jobview.monster.com/engineer-quality-jo...,NaN,Experienced (Non-Manager),58435fcab804439efdcaa7ecca0fd783
4,United States of America,US,NaN,No,jobs.monster.com,Position ID# 76162 # Positions 1 State CT C...,Shift Supervisor - Part-Time Job in Camphill,Full Time Employee,"Camphill, PA",Retail,http://jobview.monster.com/shift-supervisor-pa...,NaN,Project/Program Management,64d0272dc8496abfd9523a8df63c184c

In [21]:
keep_columns = ['job_title', 'job_description', 'location']

In [22]:
jd_df = jd_df[keep_columns]

In [23]:
jd_df.head()

,job_title,job_description,location
0,IT Support Technician Job in Madison,TeamSoft is seeing an IT Support Specialist to...,"Madison, WI 53702"
1,Business Reporter/Editor Job in Madison,The Wisconsin State Journal is seeking a flexi...,"Madison, WI 53708"
2,Johnson & Johnson Family of Companies Job Appl...,Report this job About the Job DePuy Synthes Co...,DePuy Synthes Companies is a member of Johnson...
3,Engineer - Quality Job in Dixon,Why Join Altec? If you’re considering a career...,"Dixon, CA"
4,Shift Supervisor - Part-Time Job in Camphill,Position ID# 76162 # Positions 1 State CT C...,"Camphill, PA"

In [24]:
jd_df.to_csv('datasets/cleaned_job_description.csv', index=False)

In [26]:
resume_df = pd.read_csv('datasets/resumes.csv')

In [30]:
resume_df.size

90

In [28]:
resume_df.head(10)

,Uniq Id,Crawl Timestamp,Resume Title,Location,Introduction,Work Experience,Education,Skills,Additional Information
0,3ddb29e616f31947053b257f327969d7,2019-02-20 08:47:25 +0000,Sales Manager,"New London, NH",Dynamic technical sales professional with dive...,"Sales Manager-MadgeTech, Inc-August 2015 to Fe...",B.A.-History-Franklin Pierce University-Rindge...,"120 months-CRM,72 months-Contract Negotiation,...",• Well-Developed Sales & Business Acumen ...
1,9138476c76bcbbefadedd4862966c3d2,2019-02-20 07:47:48 +0000,Implementation Engineer,"Worcester, MA","Experienced, dependable and motivated IT Techn...",Implementation Engineer-Versatile Communicatio...,"--ShoreTel University-Austin, TX|Master-PC & N...","15 months-CISCO,12 months-FIBER OPTIC,6 months...","TECHNICAL SKILLS\n\nHardware: Switches, Router..."
2,cd1cafa706f917a627982bf47291b888,2019-02-20 07:37:41 +0000,Education Information Dissemination Coordinator,"Bristol, NH",NaN,Education Information Dissemination Coordinato...,"Bachelor's-Management-Regis College-Weston, MA",NaN,NaN
3,53aea69598c6c1084e4bce89f0494bc3,2019-02-20 08:20:06 +0000,Engineering Department Intern,"Billerica, MA",To obtain full time employment in the field of...,Engineering Department Intern-Town of Billeric...,Bachelor of Science-Civil and Environmental En...,NaN,• Bachelors of Science in Civil and Environmen...
4,90f8f99d66ebc6c09fceee37aff14bc1,2019-02-20 08:35:33 +0000,Pack and Ship/SORT Technician,"Worcester, MA",NaN,Pack and Ship/SORT Technician-Intel Corporatio...,BS-Information Technology-University of Massac...,NaN,Engineering Technician/Planning Analyst/Operat...
5,fb1c760fd5311dad01e950f3062a9296,2019-02-20 06:57:56 +0000,BDC Data Analyst,"Springfield, MA",NaN,BDC Data Analyst-Gary Rome Auto Group-January ...,Bachelor of Science-Psychology-University of P...,"30 months-SIX-SIGMA,36 months-DATA ANALYSIS,24...",CORE COMPETENCIES\n• Project Management\t\t• T...
6,7795cdc183ab88aaffec73a5d99a1b82,2019-02-20 07:27:41 +0000,Safety Engineer Intern,"Boston, MA",NaN,Safety Engineer Intern-Hexagon Manufacturing I...,Master of Science-Systems Engineering-UNIVERSI...,"9 months-MATLAB,36 months-OPTIMIZATION,36 mont...","Core Competencies: Control Systems, Automotive..."
7,e219a144eca8463f5d70fdec9426466f,2019-02-20 08:15:39 +0000,Classified Ads Manager,"Allenstown, NH",To utilize experience and personal skills in t...,Classified Ads Manager-Quality of Life Publica...,NaN,NaN,NaN
8,c7c409fe9652e1eae9ecb05cce05426e,2019-02-20 08:59:32 +0000,ASSISTANT PROGRAM MANAGER,"Pembroke, NH",NaN,ASSISTANT PROGRAM MANAGER-HARBOR HOMES-August ...,CPR certified--SOUTHERN NEW HAMPSHIRE UNIVERISTY-,"13 months-PROGRAM MANAGER,0 months-RETAIL,13 m...",Skills & Abilities\nMANAGEMENT\n• 4 years of m...
9,7f562eaaa992790efe423a197bfd0ffa,2019-02-20 07:31:38 +0000,Technical Customer Service,"Plymouth, MA","High energy, hardworking Engineering graduate ...",Technical Customer Service-SmartCo Services LL...,Master of Science-EILCO-Engineering school of ...,NaN,NaN

In [29]:
print(resume_df["Additional Information"])

0    •    Well-Developed Sales & Business Acumen   ...
1    TECHNICAL SKILLS\n\nHardware: Switches, Router...
2                                                  NaN
3    • Bachelors of Science in Civil and Environmen...
4    Engineering Technician/Planning Analyst/Operat...
5    CORE COMPETENCIES\n• Project Management\t\t• T...
6    Core Competencies: Control Systems, Automotive...
7                                                  NaN
8    Skills & Abilities\nMANAGEMENT\n• 4 years of m...
9                                                  NaN
Name: Additional Information, dtype: object

In [31]:
resume_keep_columns = ['Work Experience', 'Skills', 'Additional Information', 'Education']