## data exploration on resume_df

In [1]:
import pandas as pd

In [ ]:
resume_df = pd.read_csv('datasets/resumes.csv')

In [ ]:
resume_df.size

90

In [ ]:
resume_df.head(10)

,Uniq Id,Crawl Timestamp,Resume Title,Location,Introduction,Work Experience,Education,Skills,Additional Information
0,3ddb29e616f31947053b257f327969d7,2019-02-20 08:47:25 +0000,Sales Manager,"New London, NH",Dynamic technical sales professional with dive...,"Sales Manager-MadgeTech, Inc-August 2015 to Fe...",B.A.-History-Franklin Pierce University-Rindge...,"120 months-CRM,72 months-Contract Negotiation,...",• Well-Developed Sales & Business Acumen ...
1,9138476c76bcbbefadedd4862966c3d2,2019-02-20 07:47:48 +0000,Implementation Engineer,"Worcester, MA","Experienced, dependable and motivated IT Techn...",Implementation Engineer-Versatile Communicatio...,"--ShoreTel University-Austin, TX|Master-PC & N...","15 months-CISCO,12 months-FIBER OPTIC,6 months...","TECHNICAL SKILLS\n\nHardware: Switches, Router..."
2,cd1cafa706f917a627982bf47291b888,2019-02-20 07:37:41 +0000,Education Information Dissemination Coordinator,"Bristol, NH",NaN,Education Information Dissemination Coordinato...,"Bachelor's-Management-Regis College-Weston, MA",NaN,NaN
3,53aea69598c6c1084e4bce89f0494bc3,2019-02-20 08:20:06 +0000,Engineering Department Intern,"Billerica, MA",To obtain full time employment in the field of...,Engineering Department Intern-Town of Billeric...,Bachelor of Science-Civil and Environmental En...,NaN,• Bachelors of Science in Civil and Environmen...
4,90f8f99d66ebc6c09fceee37aff14bc1,2019-02-20 08:35:33 +0000,Pack and Ship/SORT Technician,"Worcester, MA",NaN,Pack and Ship/SORT Technician-Intel Corporatio...,BS-Information Technology-University of Massac...,NaN,Engineering Technician/Planning Analyst/Operat...
5,fb1c760fd5311dad01e950f3062a9296,2019-02-20 06:57:56 +0000,BDC Data Analyst,"Springfield, MA",NaN,BDC Data Analyst-Gary Rome Auto Group-January ...,Bachelor of Science-Psychology-University of P...,"30 months-SIX-SIGMA,36 months-DATA ANALYSIS,24...",CORE COMPETENCIES\n• Project Management\t\t• T...
6,7795cdc183ab88aaffec73a5d99a1b82,2019-02-20 07:27:41 +0000,Safety Engineer Intern,"Boston, MA",NaN,Safety Engineer Intern-Hexagon Manufacturing I...,Master of Science-Systems Engineering-UNIVERSI...,"9 months-MATLAB,36 months-OPTIMIZATION,36 mont...","Core Competencies: Control Systems, Automotive..."
7,e219a144eca8463f5d70fdec9426466f,2019-02-20 08:15:39 +0000,Classified Ads Manager,"Allenstown, NH",To utilize experience and personal skills in t...,Classified Ads Manager-Quality of Life Publica...,NaN,NaN,NaN
8,c7c409fe9652e1eae9ecb05cce05426e,2019-02-20 08:59:32 +0000,ASSISTANT PROGRAM MANAGER,"Pembroke, NH",NaN,ASSISTANT PROGRAM MANAGER-HARBOR HOMES-August ...,CPR certified--SOUTHERN NEW HAMPSHIRE UNIVERISTY-,"13 months-PROGRAM MANAGER,0 months-RETAIL,13 m...",Skills & Abilities\nMANAGEMENT\n• 4 years of m...
9,7f562eaaa992790efe423a197bfd0ffa,2019-02-20 07:31:38 +0000,Technical Customer Service,"Plymouth, MA","High energy, hardworking Engineering graduate ...",Technical Customer Service-SmartCo Services LL...,Master of Science-EILCO-Engineering school of ...,NaN,NaN

In [ ]:
print(resume_df["Additional Information"])

0    •    Well-Developed Sales & Business Acumen   ...
1    TECHNICAL SKILLS\n\nHardware: Switches, Router...
2                                                  NaN
3    • Bachelors of Science in Civil and Environmen...
4    Engineering Technician/Planning Analyst/Operat...
5    CORE COMPETENCIES\n• Project Management\t\t• T...
6    Core Competencies: Control Systems, Automotive...
7                                                  NaN
8    Skills & Abilities\nMANAGEMENT\n• 4 years of m...
9                                                  NaN
Name: Additional Information, dtype: object

In [ ]:
resume_keep_columns = ['Work Experience', 'Skills', 'Education']

In [ ]:
resume_df[resume_keep_columns].head()

,Work Experience,Skills,Education
0,"Sales Manager-MadgeTech, Inc-August 2015 to Fe...","120 months-CRM,72 months-Contract Negotiation,...",B.A.-History-Franklin Pierce University-Rindge...
1,Implementation Engineer-Versatile Communicatio...,"15 months-CISCO,12 months-FIBER OPTIC,6 months...","--ShoreTel University-Austin, TX|Master-PC & N..."
2,Education Information Dissemination Coordinato...,NaN,"Bachelor's-Management-Regis College-Weston, MA"
3,Engineering Department Intern-Town of Billeric...,NaN,Bachelor of Science-Civil and Environmental En...
4,Pack and Ship/SORT Technician-Intel Corporatio...,NaN,BS-Information Technology-University of Massac...

In [ ]:
# create semantic sentence embeddings for job descriptions and resumes
jd_df["semantic_text"] = (
    "Job Title: " + jd_df["job_title"].fillna("") + ". " +
    "Location: " + jd_df["location"].fillna("") + ". " +
    "Description: " + jd_df["job_description"].fillna("") + "."
)

resume_df["semantic_text"] = (
    "Work Experience: " + resume_df["Work Experience"].fillna("") + ". " +
    "Skills: " + resume_df["Skills"].fillna("") + ". " +
    "Education: " + resume_df["Education"].fillna("") + "."
)

In [ ]:
# apply sentence transformer model to create embeddings
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('all-MiniLM-L6-v2')
jd_df["embeddings"] = jd_df["semantic_text"].apply(lambda x: model.encode(x))
resume_df["embeddings"] = resume_df["semantic_text"].apply(lambda x: model.encode(x))

README.md: 0.00B [00:00, ?B/s]

In [ ]:
# embedding dimension = 384
from sentence_transformers import util
import torch

# convert embeddings to torch tensors
jd_embeddings = torch.tensor(np.array(jd_df["embeddings"].tolist()))
resume_embeddings = torch.tensor(np.array(resume_df["embeddings"].tolist()))


cosine_scores = util.cos_sim(resume_embeddings, jd_embeddings)

In [ ]:
top_k = 3
for i in range(len(resume_df)):
    scores = cosine_scores[i]
    top_results = torch.topk(scores, k=top_k)
    print(f"\n=== Resume {i+1} ===")
    for j, score in zip(top_results.indices, top_results.values):
        j = int(j)
        print(f"JD Title: {jd_df.iloc[j]['job_title']}")
        print(f"Location: {jd_df.iloc[j]['location']}")
        print(f"Similarity: {score:.4f}")
        print("-" * 50)

=== Resume 1 ===
JD Title: SolidWorks Product and Portfolio Manager Job in Waltham
Location: Waltham, MA
Similarity: 0.5965
--------------------------------------------------
JD Title: CyberCoders Job Application for Sales Representative - Fiber Optics Solution Selling | Monster.com var MONS_LOG_VARS = {"JobID":
Location: Contact name Lauren Nesmith
Similarity: 0.5948
--------------------------------------------------
JD Title: SolidWorks Product and Portfolio Manager Job in Waltham
Location: Waltham, MA
Similarity: 0.5948
--------------------------------------------------

=== Resume 2 ===
JD Title: Slait Consulting Job Application for Telecommunications Tech | Monster.com var MONS_LOG_VARS = {"JobID":
Location: Contact name Sarah McKernan Phone 0 Fax 0 Address 4505 Cox RdSuite 100Richmond, Virginia 23060
Similarity: 0.6384
--------------------------------------------------
JD Title: Central Office Services Manager - Quantico
Location: Mcb Quantico, VA 22134
Similarity: 0.6289
--------------------------------------------------
JD Title: Monster
Location: If you are a Senior Telecommunications Engineer with experience, please read on!Location: Baltimore, MDSalary Range: $80-105,000What You Will Be Doing•Plan, design, implement, and provide ongoing support of Telecom solutions (Avaya, Mitel, Cloud) of high complexity to fulfill business needs for performance and cost benefits •Serve as a technical lead for hardware installation, configuration, and operational support of Telecom infrastructure. •Provide 2nd level technical support to clients and to technical teams within Mariner Finance to resolve telecom issues and to support the implementation of new solutions •Evaluate new technology and bring opportunities forward that would improve the future Telecom architecture, performance, and services •Ensure full compliance of Mariner’s Key Controls and Technical Service Requirements for all Telecom architecture, designs, and implementations both past and present •Ensure all changes go through appropriate review, change control, and acceptance before implementation •Lead development, testing and QA functions to ensure that projects are securely delivered and fulfill expectations •Build and maintain relationships with teams and third parties on Telecom development or support issues •Provide highest level of technical consultancy to ensure problem resolution is achieved in the shortest possible timeframe •Work with the Information Security team to ensure solutions deployed meet Mariner’s security requirements and provide technical assistance for investigation and analysis of security alerts •Development of processes and procedures for use by the IT Ops Team and third parties in the management of Telecom environmentsWhat You Need for this PositionMore Than 5 Years of experience and knowledge of:- Avaya or Mitel systems- PBX- IVR- vbscript or PowerShellWhat's In It for You•Competitive Salary •Medical, Dental, Vision, Life Insurances •401k Match •Paid Time-Off •Education Reimbursement •Flexible Spending AccountSo, if you are a Senior Telecommunications Engineer with experience, please apply today!Or send your resume to Taylor@CyberCoders.com
Similarity: 0.6287
--------------------------------------------------

=== Resume 3 ===
JD Title: Clinical Therapist – Bethesda NH Youth Center Job in Bethesda
Location: Bethesda, OH
Similarity: 0.5743
--------------------------------------------------
JD Title: Wellness Coordinator-Mental Health/Public Health Job in Saint Paul
Location: Saint Paul, MN 55114
Similarity: 0.5563
--------------------------------------------------
JD Title: Family Life Services Mental Health Therapist II Job in Montoursville
Location: Montoursville, PA 17754
Similarity: 0.5463
--------------------------------------------------

=== Resume 4 ===
JD Title: Project Manager - Water & Wastewater /Construction/AutoCAD Job in Washington
Location: Washington, DC 20001
Similarity: 0.5373
--------------------------------------------------
JD Title: Project Manager - Water & Wastewater /Construction/AutoCAD Job in Washington
Location: Washington, DC 20001
Similarity: 0.5373
--------------------------------------------------
JD Title: - Field Service Engineer Job in Billerica
Location: Job Details
Similarity: 0.5338
--------------------------------------------------

=== Resume 5 ===
JD Title: EG Workforce Solutions Job Application for Production/Assembly Associates - DENSO Manufacturing | Monster.com var MONS_LOG_VARS = {"JobID":
Location: Contact name Naydena Smith Phone 269-660-3502 Address Battle Creek, MI
Similarity: 0.5412
--------------------------------------------------
JD Title: EG Workforce Solutions Job Application for Production/Assembly Associates - DENSO Manufacturing | Monster.com var MONS_LOG_VARS = {"JobID":
Location: Contact name Naydena Smith Phone 269-660-3502 Address Battle Creek, MI
Similarity: 0.5412
--------------------------------------------------
JD Title: Assembly and Test Process Area Manager  Job in Sunnyvale
Location: Sunnyvale, CA
Similarity: 0.5361
--------------------------------------------------

=== Resume 6 ===
JD Title: Monster
Location: HELP DESK ANALYSTClient’s Need:ChaseSource has a large client that is currently working on a special project in partnership with state and federal agencies to develop new internal infrastructure. The client knows that with the right people on board, anything is possible.The Help Desk Analyst will support internal staff over the phone and via Service Now ticketing system. The successful candidate will require an aptitude for working with applications/systems to undertake analysis, diagnosis and resolution of staff problems.JOB DETAILSLocation: Austin, TXHours: Full TimePay Range: $14 - $15 HourlyType: Long Term ContractRESPONSIBILITIESAct as a single point of contact for phone calls from staff regarding IT issues and inquiriesReceiving, logging and managing calls from internal staff via telephoneFirst line support - troubleshooting of IT related problems from in-house software to hardware, such as smart phones, laptops, PCs and printers and iPadsTroubleshoot basic network issues such as down sites/phone outagesEscalate unresolved calls to the 2nd line supportLog all calls in the Service Now logging systemMaintain a high degree of customer service for all support queries and adhere to all service management principlesUtilize in house knowledge-base in order to assist with triageIdentify major incidents and notify 2nd line support in a timely fashionBasic Active Directory knowledge. Ability to check user accounts for required matching securityNavigate Active Directory to check user accounts for appropriate security access and perform password resetsEDUCATION/EXPERIENCEHigh school diploma or equivalent requiredMinimum of 2 year work experience with Help Desk Support...Company OverviewChaseSource is a dynamic and rapidly growing, entrepreneurial company. We specialize in providing recruitment solutions to a variety of industries including, Healthcare, Energy, IT, and Telecommunications. We focus on producing a high quality product, taking the time to ensure an opportunity is the right fit for both the candidate and client.
Similarity: 0.6822
--------------------------------------------------
JD Title: Client Operations Representative Job in Atlanta
Location: Atlanta, GA
Similarity: 0.6375
--------------------------------------------------
JD Title: CBM of America – Communications Technologies Solutions Job Application for Lead Telecommunications Central Office Installer | Monster.com var MONS_LOG_VARS = {"JobID":
Location: Contact name Matt Hannam Phone 954-246-1581 Fax 239-236-1253 Address Deerfield Beach, FL, FL
Similarity: 0.6282
--------------------------------------------------

=== Resume 7 ===
JD Title: Pendleton Resources Job Application for Safety Manager | Monster.com var MONS_LOG_VARS = {"JobID":
Location: Contact name Wanda Quallo Phone 3038328100 Address 1120 Lincoln St. , Ste. 702Denver, CO 80203
Similarity: 0.6128
--------------------------------------------------
JD Title: Production Planner - Tier  Automotive Supplier Job in Lexington
Location: Lexington, KY 40508
Similarity: 0.6106
--------------------------------------------------
JD Title: Production Manager II # Job in Clayton
Location: Clayton, NJ
Similarity: 0.6048
--------------------------------------------------

=== Resume 8 ===
JD Title: Full Time Position - Immediate Hire / No Experience Necessary Job in Marlton
Location: Marlton, NJ 08053
Similarity: 0.5758
--------------------------------------------------
JD Title: Customer Service Representative Job in New York
Location: New York, NY 10035
Similarity: 0.5634
--------------------------------------------------
JD Title: Full Time - Manager Trainee - No Weekends Job in Columbus
Location: Columbus, OH
Similarity: 0.5615
--------------------------------------------------

=== Resume 9 ===
JD Title: Schafer Richardson Job Application for Property Management Assistant | Monster.com var MONS_LOG_VARS = {"JobID":
Location: Property Management Assistant  Salary:  DOQJob Category: AdministrationLocation:  Minneapolis, MN 55401Status: Full Time Summary:Schafer Richardson, Inc. specializes in providing quality investment, management, leasing, development and construction services to the commercial and housing real estate industry in the Twin Cities.  We have an exciting opportunity in our Property Management and Leasing division consisting of 37 properties.  We are seeking a motivated self- starter with the ability to multi-task in a high paced environment while remaining focused on tasks at hand. Duties and Responsibilities included below.  Other duties may be assigned as necessary.Process and track leases, tenant information and property data ensuring all lease transactions and related documents have been prepared and processed correctly.Create and disseminate lease transaction documentation such as lease abstracts, rent rolls, commencement letters, welcome packages, and related documentation.Process new lease or renewal lease documentation in the Yardi Accounting System and manage a list of lease options, terms and conditions, and special clauses in the lease transactions.Supportleasing team in preparation of proposals confirming rent calculations, commissions, tenant improvements and other costs or allowances.Provide assistance to marketing person in editing marketing brochures and update property information on website and commercial real estate portals.Support Property Managers in preparation of estoppels, default notices, tenant correspondence other department documentation.Track and maintain a database for certificates of insurance for tenants, purchase orders and judgements and provide assistance in collecting data.Update tenant and vendor contact lists, contract lists, and manage central database systems for Property Management and Leasing DepartmentDispatch maintenance or vendors to properties when needed and other general office duties such as copying, filing, taking meeting notes or ordering supplies Education/Experience:Associated Degree minimum, Bachelor’s Degree preferred.5 years of professional administrative experience.A back ground in real estate and candidate with a sales person real estate license would be ideal. Knowledge, Skills and Other Abilities:Knowledge of Yardi Accounting Software or Argus is helpful, but not required.Computer proficiency as well as a working knowledge is required specifically with Adobe Photoshop Illustrator, Microsoft Word, Excel, PowerPoint and InDesign.Candidate must be detail oriented and well organized while possessing strong time management skills and a sense of urgency for meeting critical deadlines.Ability to communicate effectively and identify and resolve problems.Focused and self-motivated team player who must be able to work independently while handling multiple tasks and paying strict attention to detail      Please send resume and salary requirements to:   Cynthia J. Schultz, CCIMSchafer Richardson, Inc. 900 North Third StreetMinneapolis, MN 55401or viaemail to cschultz@sr-re.com Physical Demands:The physical demands described here are representative of those that must be met by an employee to successfully perform the essential functions of this job.  Reasonable accommodations may be made to enable individuals with disabilities to perform the essential functions. The employee in this position must frequently communicate with employees and must be able to exchange accurate information in these situations. While performing the duties of this job, the employee must beabletoremaininastationary position50percent ofthetime.  The employee constantly operates a computer and other office productivity machinery (i.e., a computer, copy machine, and computer printer. In addition will occasionally lift and/or move up to 15 pounds and occasionally moves about inside the office to access computer equipment in different office locations.  Travel:0%
Similarity: 0.6689
--------------------------------------------------
JD Title: Property Management Company is seeking Administrative Assistant! Job in Los Angeles
Location: Los Angeles, CA 90025
Similarity: 0.6454
--------------------------------------------------
JD Title: Administrative Assistant Opportunity in Property Management! Job in Los Angeles
Location: Los Angeles, CA 90071
Similarity: 0.6420
--------------------------------------------------

=== Resume 10 ===
JD Title: Technical Sales Specialist (Northern CA) Job in San Francisco
Location: San Francisco, CA
Similarity: 0.6559
--------------------------------------------------
JD Title: Variable Refrigerant Flow / VRF Sales Engineer Job in Dallas
Location: Dallas, TX 75201
Similarity: 0.6274
--------------------------------------------------
JD Title: Commodity Leader -- Electronics
Location: Fort Wayne, IN
Similarity: 0.6059
--------------------------------------------------