## Data exploration on jd_df

In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [10]:
jd_df = pd.read_csv('datasets/job_description.csv')

In [11]:
jd_df.head()

,country,country_code,date_added,has_expired,job_board,job_description,job_title,job_type,location,organization,page_url,salary,sector,uniq_id
0,United States of America,US,NaN,No,jobs.monster.com,TeamSoft is seeing an IT Support Specialist to...,IT Support Technician Job in Madison,Full Time Employee,"Madison, WI 53702",NaN,http://jobview.monster.com/it-support-technici...,NaN,IT/Software Development,11d599f229a80023d2f40e7c52cd941e
1,United States of America,US,NaN,No,jobs.monster.com,The Wisconsin State Journal is seeking a flexi...,Business Reporter/Editor Job in Madison,Full Time,"Madison, WI 53708",Printing and Publishing,http://jobview.monster.com/business-reporter-e...,NaN,NaN,e4cbb126dabf22159aff90223243ff2a
2,United States of America,US,NaN,No,jobs.monster.com,Report this job About the Job DePuy Synthes Co...,Johnson & Johnson Family of Companies Job Appl...,"Full Time, Employee",DePuy Synthes Companies is a member of Johnson...,Personal and Household Services,http://jobview.monster.com/senior-training-lea...,NaN,NaN,839106b353877fa3d896ffb9c1fe01c0
3,United States of America,US,NaN,No,jobs.monster.com,Why Join Altec? If you’re considering a career...,Engineer - Quality Job in Dixon,Full Time,"Dixon, CA",Altec Industries,http://jobview.monster.com/engineer-quality-jo...,NaN,Experienced (Non-Manager),58435fcab804439efdcaa7ecca0fd783
4,United States of America,US,NaN,No,jobs.monster.com,Position ID# 76162 # Positions 1 State CT C...,Shift Supervisor - Part-Time Job in Camphill,Full Time Employee,"Camphill, PA",Retail,http://jobview.monster.com/shift-supervisor-pa...,NaN,Project/Program Management,64d0272dc8496abfd9523a8df63c184c

In [12]:
location_delete = jd_df['location'].astype(str).str.startswith('Contact')
print(location_delete)

0        False
1        False
2        False
3        False
4        False
         ...
21995    False
21996    False
21997    False
21998    False
21999    False
Name: location, Length: 22000, dtype: bool

In [13]:
jd_df = jd_df[~location_delete]

In [14]:
jd_df.head(20)

,country,country_code,date_added,has_expired,job_board,job_description,job_title,job_type,location,organization,page_url,salary,sector,uniq_id
0,United States of America,US,NaN,No,jobs.monster.com,TeamSoft is seeing an IT Support Specialist to...,IT Support Technician Job in Madison,Full Time Employee,"Madison, WI 53702",NaN,http://jobview.monster.com/it-support-technici...,NaN,IT/Software Development,11d599f229a80023d2f40e7c52cd941e
1,United States of America,US,NaN,No,jobs.monster.com,The Wisconsin State Journal is seeking a flexi...,Business Reporter/Editor Job in Madison,Full Time,"Madison, WI 53708",Printing and Publishing,http://jobview.monster.com/business-reporter-e...,NaN,NaN,e4cbb126dabf22159aff90223243ff2a
2,United States of America,US,NaN,No,jobs.monster.com,Report this job About the Job DePuy Synthes Co...,Johnson & Johnson Family of Companies Job Appl...,"Full Time, Employee",DePuy Synthes Companies is a member of Johnson...,Personal and Household Services,http://jobview.monster.com/senior-training-lea...,NaN,NaN,839106b353877fa3d896ffb9c1fe01c0
3,United States of America,US,NaN,No,jobs.monster.com,Why Join Altec? If you’re considering a career...,Engineer - Quality Job in Dixon,Full Time,"Dixon, CA",Altec Industries,http://jobview.monster.com/engineer-quality-jo...,NaN,Experienced (Non-Manager),58435fcab804439efdcaa7ecca0fd783
4,United States of America,US,NaN,No,jobs.monster.com,Position ID# 76162 # Positions 1 State CT C...,Shift Supervisor - Part-Time Job in Camphill,Full Time Employee,"Camphill, PA",Retail,http://jobview.monster.com/shift-supervisor-pa...,NaN,Project/Program Management,64d0272dc8496abfd9523a8df63c184c
5,United States of America,US,NaN,No,jobs.monster.com,Job Description Job #: 720298Apex Systems has...,Construction PM - Charlottesville Job in Charl...,Full Time Employee,"Charlottesville, VA",Computer/IT Services,http://jobview.monster.com/construction-pm-cha...,NaN,Experienced (Non-Manager),1e2637cb5f7a2c4615a99a26c0566c66
7,United States of America,US,NaN,No,jobs.monster.com,RESPONSIBILITIES:Kforce has a client seeking a...,Mailroom Clerk Job in Austin,Full Time Employee,"Austin, TX 73301",NaN,http://jobview.monster.com/mailroom-clerk-job-...,NaN,Experienced (Non-Manager),549a0541e4452ecd155efc032aaa72d7
8,United States of America,US,NaN,No,jobs.monster.com,"Part-Time, 4:30 pm - 9:30 pm, Mon - Fri Brookd...",Housekeeper Job in Austin,Part Time Employee,"Austin, TX 78746",Hotels and Lodging Personal and Household Serv...,http://jobview.monster.com/housekeeper-job-aus...,NaN,Customer Support/Client Care,a6a2b5e825b8ce1c3b517adb2497c5ed
9,United States of America,US,NaN,No,jobs.monster.com,"Insituform Technologies, LLC, an Aegion compan...",Video Data Management /Transportation Technici...,NaN,"Chesterfield, MO",NaN,http://jobview.monster.com/video-data-manageme...,NaN,NaN,73a9ba2b706e02628fa22ca1357174b1
10,United States of America,US,NaN,No,jobs.monster.com,Aflac Insurance Sales Agent While a career in ...,Aflac Insurance Sales Agent Job in Berryville,Full Time,"Berryville, VA 22611",Insurance,http://jobview.monster.com/aflac-insurance-sal...,NaN,Customer Support/Client Care,2f8bdf60db4d85627ab8f040e67aa78d
11,United States of America,US,NaN,No,jobs.monster.com,Enjoy making a great first impression? Our Sal...,Sales Associate Job in Columbus,Full Time Employee,"Columbus, IN",Business Services - Other,http://jobview.monster.com/Sales-Associate-Job...,NaN,Customer Support/Client Care,3a2adeacbf35985a508f630661eebb43
12,United States of America,US,NaN,No,jobs.monster.com,Junior ProofreaderOur client's in- house creat...,Junior Proofreader Job in Boston,Full Time,"Boston, MA",NaN,http://jobview.monster.com/Junior-Proofreader-...,NaN,NaN,dd244d1299cf62058c71cef022bcfab3
13,United States of America,US,NaN,No,jobs.monster.com,Launch your teaching career with the Leader in...,Primrose Private Preschool Teacher Job in Houston,Full Time,"Houston, TX 77098",Education,http://jobview.monster.com/Primrose-Private-Pr...,9.00 - 13.00 $ /hour,Entry Level,b43c077756d5a326c4854e1399fd2464
14,United States of America,US,NaN,No,jobs.monster.com,Construction Professional For more than 15 yea...,Superintendent Job in Houston,Full Time Employee,"Houston, TX",Construction - Industrial Facilities and Infra...,http://jobview.monster.com/Superintendent-Job-...,"80,000.00 - 95,000.00 $ /year",Building Construction/Skilled Trades,d8491fcefe14d1398de419984dccf427
15,United States of America,US,NaN,No,jobs.monster.com,CenturyLink (NYSE: CTL) is a global communicat...,Engineer II - Outside Plant Engineer Job in De...,Full Time Employee,"Des Moines, IA 50317",NaN,http://jobview.monster.com/Engineer-II-Outside...,NaN,NaN,5d8434d45f730aa4fc040c5fa7495cde
16,United States of America,US,NaN,No,jobs.monster.com,Airfields. Roads. Dams. Buildings. Name the pr...,Horizontal Construction Engineers Job in Wades...,NaN,Wadesboro 28170,NaN,http://jobview.monster.com/Horizontal-Construc...,NaN,Civil & Structural EngineeringGeneral/Other: E...,c43a1fc560511962321dbf21df14fe49
17,United States of America,US,NaN,No,jobs.monster.com,We are currently seeking ambitious and persona...,Pest Control Technician – Field Service Rep (E...,"Full Time, Employee","Denver, CO",Accounting and Auditing Services,http://jobview.monster.com/Pest-Control-Techni...,NaN,Installation/Maintenance/Repair,8d8f39de4a07929a92c2e6dd7a72a0af
18,United States of America,US,NaN,No,jobs.monster.com,Job SummaryDo you have a strong aptitude for w...,Content Developer for MATLAB Code Generation J...,Full Time,"Natick, MA",Education,http://jobview.monster.com/Content-Developer-f...,NaN,Experienced (Non-Manager),426ea422646470737cb364453e94f38a
19,United States of America,US,NaN,No,jobs.monster.com,"Competitive compensation package, excellent co...",Technician - Robot & Multi-Axis CNC Field Serv...,Full Time,"Carter Lake, IA 51510",NaN,http://jobview.monster.com/Technician-Robot-Mu...,"60,000.00 - 72,000.00 $ /year",Experienced (Non-Manager),3bef462fc38d743c7fbce17cf50ee7d5
20,United States of America,US,NaN,No,jobs.monster.com,Business & Strategy AnalystOne of our top clie...,Business & Strategy Analyst Job in Houston,"Full Time, Employee","Houston, TX",Legal Services,http://jobview.monster.com/Business-amp-Strate...,NaN,Business/Strategic Management,9331cb7b561348a692f7afc58ac78926

In [15]:
jd_df[jd_df['location'].str.len() > 50][['job_title', 'location']]

,job_title,location
2,Johnson & Johnson Family of Companies Job Appl...,DePuy Synthes Companies is a member of Johnson...
45,Respiratory Therapist PRN Nights - Kindred Hos...,Respiratory Therapist PRN Nights - Kindred Hos...
105,Registered Nurse ICU Full Time Days - Kindred ...,Registered Nurse ICU Full Time Days - Kindred ...
115,Experienced Registered Nurse-Critical Care/ICU...,Experienced Registered Nurse-Critical Care/ICU...
138,Registered Nurse ICU Full Time Nights - Kindre...,Registered Nurse ICU Full Time Nights - Kindre...
...,...,...
21831,HR Assistant Job in Chicago,Contract HR AssistantPay Rate: $15-$25/hr.; De...
21880,Junior Accountant Job in Chicago,Location: ChicagoPay rate 18.00-20.00Contract/...
21899,Associate Customer Business Manager Job in Cin...,Associate Customer Business Manager Location: ...
21944,Maintenance Planner Job in Cincinnati,Maintenance Planner-16150DescriptionLocation: ...
21963,Consultant Security Network Job in Cincinnati,Job Title:Consultant Security NetworkJob Descr...

In [16]:
jd_df = jd_df[jd_df['location'].str.len().between(5, 50)]

In [17]:
import re
jd_df = jd_df.copy()

def clean_location(text):
    text = str(text).strip()
    match = re.search(r"[A-Za-z\s]+,\s*[A-Z]{2}$", text)
    return match.group(0) if match else None

jd_df['location_cleaned'] = jd_df['location'].apply(clean_location)

In [18]:
jd_df.head()

,country,country_code,date_added,has_expired,job_board,job_description,job_title,job_type,location,organization,page_url,salary,sector,uniq_id,location_cleaned
0,United States of America,US,NaN,No,jobs.monster.com,TeamSoft is seeing an IT Support Specialist to...,IT Support Technician Job in Madison,Full Time Employee,"Madison, WI 53702",NaN,http://jobview.monster.com/it-support-technici...,NaN,IT/Software Development,11d599f229a80023d2f40e7c52cd941e,None
1,United States of America,US,NaN,No,jobs.monster.com,The Wisconsin State Journal is seeking a flexi...,Business Reporter/Editor Job in Madison,Full Time,"Madison, WI 53708",Printing and Publishing,http://jobview.monster.com/business-reporter-e...,NaN,NaN,e4cbb126dabf22159aff90223243ff2a,None
3,United States of America,US,NaN,No,jobs.monster.com,Why Join Altec? If you’re considering a career...,Engineer - Quality Job in Dixon,Full Time,"Dixon, CA",Altec Industries,http://jobview.monster.com/engineer-quality-jo...,NaN,Experienced (Non-Manager),58435fcab804439efdcaa7ecca0fd783,"Dixon, CA"
4,United States of America,US,NaN,No,jobs.monster.com,Position ID# 76162 # Positions 1 State CT C...,Shift Supervisor - Part-Time Job in Camphill,Full Time Employee,"Camphill, PA",Retail,http://jobview.monster.com/shift-supervisor-pa...,NaN,Project/Program Management,64d0272dc8496abfd9523a8df63c184c,"Camphill, PA"
5,United States of America,US,NaN,No,jobs.monster.com,Job Description Job #: 720298Apex Systems has...,Construction PM - Charlottesville Job in Charl...,Full Time Employee,"Charlottesville, VA",Computer/IT Services,http://jobview.monster.com/construction-pm-cha...,NaN,Experienced (Non-Manager),1e2637cb5f7a2c4615a99a26c0566c66,"Charlottesville, VA"

In [19]:
jd_df = jd_df.dropna(subset=['location_cleaned']).copy()

In [20]:
keep_columns = ['job_title', 'job_description', 'location_cleaned']

In [21]:
jd_df = jd_df[keep_columns]

In [22]:
jd_df.head(20)

,job_title,job_description,location_cleaned
3,Engineer - Quality Job in Dixon,Why Join Altec? If you’re considering a career...,"Dixon, CA"
4,Shift Supervisor - Part-Time Job in Camphill,Position ID# 76162 # Positions 1 State CT C...,"Camphill, PA"
5,Construction PM - Charlottesville Job in Charl...,Job Description Job #: 720298Apex Systems has...,"Charlottesville, VA"
9,Video Data Management /Transportation Technici...,"Insituform Technologies, LLC, an Aegion compan...","Chesterfield, MO"
11,Sales Associate Job in Columbus,Enjoy making a great first impression? Our Sal...,"Columbus, IN"
12,Junior Proofreader Job in Boston,Junior ProofreaderOur client's in- house creat...,"Boston, MA"
14,Superintendent Job in Houston,Construction Professional For more than 15 yea...,"Houston, TX"
17,Pest Control Technician – Field Service Rep (E...,We are currently seeking ambitious and persona...,"Denver, CO"
18,Content Developer for MATLAB Code Generation J...,Job SummaryDo you have a strong aptitude for w...,"Natick, MA"
20,Business & Strategy Analyst Job in Houston,Business & Strategy AnalystOne of our top clie...,"Houston, TX"
24,Construction Healthcare Superintendent / Hospi...,Our client is a leader in the construction of ...,"Houston, TX"
26,AT&T Business Sales Leadership Development Pro...,Our business sales professionals are elite sel...,"Denver, CO"
28,Resident Care Specialist,Resident Care Specialist DescriptionSummaryPro...,"Houston, TX"
31,RECREATION THERAPY ASSISTANT Job in Knoxville,RECREATION THERAPY ASSISTANT The successful a...,"Knoxville, TN"
35,Technical Writer w/ TS Clearance Job in Washin...,MTI is looking for a talented Technical Writer...,"Washington, DC"
41,Japanese and English Speaking Interpreter and ...,Job Description: Technical Japanese/English S...,"Charleston, WV"
53,Software Engineer Job in Fort Wayne,A Fortune 500 and worldwide leader in business...,"Fort Wayne, IN"
56,CASHIER Job in Houston,DescriptionIf your goal is to begin a fantasti...,"Houston, TX"
59,Technical Writer - Documentation Job in Ogden,Maden Technologies is accepting applications f...,"Ogden, UT"
61,Upscale Casual Restaurant Managers- Gm - Agm -...,MUST HAVE CURRENT RESTAURANT MANAG...,"Houston, TX"

In [23]:
jd_df.to_csv('datasets/cleaned_jd_location.csv', index=False)