In [32]:
import pandas as pd

## Raw dataset
data= pd.read_csv("../0_raw_dataset/Resume.csv")

In [33]:
data.head()

,ID,Resume_str,Resume_html,Category
0,16852973,HR ADMINISTRATOR/MARKETING ASSOCIATE\...,"<div class=""fontsize fontface vmargins hmargin...",HR
1,22323967,"HR SPECIALIST, US HR OPERATIONS ...","<div class=""fontsize fontface vmargins hmargin...",HR
2,33176873,HR DIRECTOR Summary Over 2...,"<div class=""fontsize fontface vmargins hmargin...",HR
3,27018550,HR SPECIALIST Summary Dedica...,"<div class=""fontsize fontface vmargins hmargin...",HR
4,17812897,HR MANAGER Skill Highlights ...,"<div class=""fontsize fontface vmargins hmargin...",HR

In [34]:
resume_df=data[[
    "ID",
    "Resume_str", "Category"
]]
resume_df

            ID                                         Resume_str  Category
0     16852973           HR ADMINISTRATOR/MARKETING ASSOCIATE\...        HR
1     22323967           HR SPECIALIST, US HR OPERATIONS      ...        HR
2     33176873           HR DIRECTOR       Summary      Over 2...        HR
3     27018550           HR SPECIALIST       Summary    Dedica...        HR
4     17812897           HR MANAGER         Skill Highlights  ...        HR
...        ...                                                ...       ...
2479  99416532           RANK: SGT/E-5 NON- COMMISSIONED OFFIC...  AVIATION
2480  24589765           GOVERNMENT RELATIONS, COMMUNICATIONS ...  AVIATION
2481  31605080           GEEK SQUAD AGENT         Professional...  AVIATION
2482  21190805           PROGRAM DIRECTOR / OFFICE MANAGER    ...  AVIATION
2483  37473139           STOREKEEPER II       Professional Sum...  AVIATION

[2484 rows x 3 columns]

In [35]:
exclude = ["CHEF", "AGRICULTURE", "BPO"]

resume_df_s = (
    resume_df[~resume_df["Category"].isin(exclude)]
    .sample(n=100, random_state=42)
)
resume_df_sample=resume_df_s[[
    "ID",
    "Resume_str"
]]
resume_df_sample.to_csv("../1_data_cleaning/resume_cleaned.csv", index=False)
resume_df_s.to_csv("../5_checking_accuracy/Resume.csv", index=False)

In [37]:
resume_df_sample.head(5)

            ID                                         Resume_str
247   11580408           INFORMATION TECHNOLOGY COORDINATOR   ...
1926  99433371           CONSTRUCTION       Executive Summary ...
2305  22848179           DIRECTOR OF COMMUNITY             Ski...
1972  94503308           FACILITIES CONSTRUCTION MANAGER      ...
2160  69243180           SR. MORTGAGE BANKING EXECUTIVE       ...

In [36]:
resume_df_s.head(5)

,ID,Resume_str,Category
247,11580408,INFORMATION TECHNOLOGY COORDINATOR ...,INFORMATION-TECHNOLOGY
1926,99433371,CONSTRUCTION Executive Summary ...,CONSTRUCTION
2305,22848179,DIRECTOR OF COMMUNITY Ski...,ARTS
1972,94503308,FACILITIES CONSTRUCTION MANAGER ...,CONSTRUCTION
2160,69243180,SR. MORTGAGE BANKING EXECUTIVE ...,BANKING