In [2]:
import pandas as pd

## Raw dataset
data= pd.read_csv("../0_raw_dataset/Resume.csv")

In [3]:
data.head()

,ID,Resume_str,Resume_html,Category
0,16852973,HR ADMINISTRATOR/MARKETING ASSOCIATE\...,"<div class=""fontsize fontface vmargins hmargin...",HR
1,22323967,"HR SPECIALIST, US HR OPERATIONS ...","<div class=""fontsize fontface vmargins hmargin...",HR
2,33176873,HR DIRECTOR Summary Over 2...,"<div class=""fontsize fontface vmargins hmargin...",HR
3,27018550,HR SPECIALIST Summary Dedica...,"<div class=""fontsize fontface vmargins hmargin...",HR
4,17812897,HR MANAGER Skill Highlights ...,"<div class=""fontsize fontface vmargins hmargin...",HR

In [5]:
resume_df=data[[
    "ID",
    "Resume_str"
]]
resume_df

            ID                                         Resume_str
0     16852973           HR ADMINISTRATOR/MARKETING ASSOCIATE\...
1     22323967           HR SPECIALIST, US HR OPERATIONS      ...
2     33176873           HR DIRECTOR       Summary      Over 2...
3     27018550           HR SPECIALIST       Summary    Dedica...
4     17812897           HR MANAGER         Skill Highlights  ...
...        ...                                                ...
2479  99416532           RANK: SGT/E-5 NON- COMMISSIONED OFFIC...
2480  24589765           GOVERNMENT RELATIONS, COMMUNICATIONS ...
2481  31605080           GEEK SQUAD AGENT         Professional...
2482  21190805           PROGRAM DIRECTOR / OFFICE MANAGER    ...
2483  37473139           STOREKEEPER II       Professional Sum...

[2484 rows x 2 columns]

In [6]:
resume_df.to_csv("../1_data_cleaning/resume_cleaned.csv", index=False)